# Site settings
title: Devoll
email: tony@325studio.com 
description: > # this means to ignore newlines until "baseurl:"
  325 Studio can help with brand identity to marketing and user experience to digital experiences, we can help your company look great and have an impact on your customers.

baseurl: "gracious-wescoff-4359f8.netlify.com" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"