url: https://gracious-wescoff-4359f8.netlify.com/
baseurl: https://gracious-wescoff-4359f8.netlify.com/

# Site settings
title: 325 Studio
email: tony@325studio.com
description: "325 Studio is a full service creative design studio. We help businesses look great through brand identity, logos, marketing design, website design, user exerpience design, product design, and development"


# Team names, titles and social links
people:
- name: Tony Naccarato
  pic: 1
  position: Founder & Creative Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/325studio/

# Postal address (add as many lines as necessary)
address:
  - line: Salt Lake City, Utah area

# Build settings
markdown: kramdown
permalink: pretty